<a href="https://colab.research.google.com/github/sheshank1436/pytorch/blob/master/pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 This is the first Part of pytorch training from basics

In [24]:
#import pytorch
import torch


In [25]:
#scalar
t1=torch.tensor(1)
print(t1.dtype)
print(t1)
t1=torch.tensor(2,dtype=float)
print(t1)

torch.int64
tensor(1)
tensor(2., dtype=torch.float64)


In [26]:
#vector
t2=torch.tensor([1,3,2,4])
print(t2.dtype)
print(t2)

torch.int64
tensor([1, 3, 2, 4])


In [27]:
#2dim array
t3=torch.tensor([[1,3],[3,4],[1,4]])
print(t3.dtype)
print(t3)
print(t3.shape)

torch.int64
tensor([[1, 3],
        [3, 4],
        [1, 4]])
torch.Size([3, 2])


In [28]:
#3dim array(tensors)
t4=torch.tensor([[1,3,3],[3,4,5],[1,4,6]])
print(t4.dtype)
print(t4)
print('shape of tensor:',t4.shape)

torch.int64
tensor([[1, 3, 3],
        [3, 4, 5],
        [1, 4, 6]])
shape of tensor: torch.Size([3, 3])


In [29]:
#addition
x=torch.tensor([1.,3.,2.],requires_grad=True)
m=torch.tensor([2,2,2])
c=torch.tensor([1,1,1])
y=m*x+c
print(y)

tensor([3., 7., 5.], grad_fn=<AddBackward0>)


In [30]:
a=torch.tensor(1.,requires_grad=True)
b=torch.tensor(11.,requires_grad=True)
c=torch.tensor(5.)
g=a*b+c
print(g)

tensor(16., grad_fn=<AddBackward0>)


In [31]:
g.backward()

In [32]:
print('dg/da',a.grad)

dg/da tensor(11.)


In [33]:
print('dg/db',b.grad)

dg/db tensor(1.)


In [34]:
import numpy as np

In [35]:
a=np.array([[1,2],[1,3]])
print(a)
print(a.dtype)

[[1 2]
 [1 3]]
int64


In [36]:
#CONVERSION OF NUMPY ARRAYS TO TENSORS
b=torch.from_numpy(a)
print(b)
print(b.dtype)
print(type(b))

tensor([[1, 2],
        [1, 3]])
torch.int64
<class 'torch.Tensor'>


In [37]:
#conversion of tensors back to numpy  array
c=b.numpy()
print(type(c))
print(c)

<class 'numpy.ndarray'>
[[1 2]
 [1 3]]


In [38]:
#regression with tensors without using any inbuilt functions
inputs=np.array([[73,67,43],
                 [91,88,64],
                 [87,134,58],
                 [102,43,37],
                 [69,96,70]],dtype='float32')
outputs=np.array([[56,70],
                 [81,101],
                 [119,133],
                 [22,37],
                 [103,119]],dtype='float32')

In [39]:
type(inputs)

numpy.ndarray

In [40]:
input=torch.from_numpy(inputs)
output=torch.from_numpy(outputs)


In [41]:
input

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [42]:
output

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

here for weights column we took the shape as (2,3 ) which we will transpose to make it (3,2) in order to multiply with 3 input cols of input
we took 3 because we have 3 input cols and 2 because we have two ouputs for one input row
WE HAVE used requires_grad=True here because we provide it only to the variables which will change
like in regression we wont change the inputs but instead we change the value of weights and biases  to see which weights provides us the least loss values

In [43]:

w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)
print(w,b)


tensor([[ 0.5977, -0.0045,  0.1303],
        [-1.7474, -0.6449,  1.3878]], requires_grad=True) tensor([ 1.3012, -0.6571], requires_grad=True)


In [ ]:
yp=input@w.t()+b
yp

tensor([[  11.1586, -235.4209],
        [  13.1270, -313.6221],
        [ -32.3780, -380.4171],
        [  54.1985, -213.4543],
        [ -10.1148, -314.8095]], grad_fn=<AddBackward0>)

you will see below tha addition of  tensors is different from traditional matrix addition.
in matrix if you use two matrices of different dimension it does not accept.
but in tensors it does accept if you try to add [5,2] matrix with [1,2]
what it does is the same [1,2]matrix becomes [5,2] with same values.


In [49]:

a=torch.randn(5,2,requires_grad=True)

b=torch.randn(2,requires_grad=True)
print(a)

tensor([[-0.2021,  1.0551],
        [-1.1494,  0.2417],
        [-1.2496,  0.3870],
        [-0.4944,  0.2600],
        [-0.1855,  0.6887]], requires_grad=True)


In [50]:
b

tensor([0.6211, 0.7784], requires_grad=True)

In [51]:
a+b

tensor([[ 0.4191,  1.8335],
        [-0.5282,  1.0201],
        [-0.6285,  1.1654],
        [ 0.1267,  1.0384],
        [ 0.4356,  1.4671]], grad_fn=<AddBackward0>)

In [52]:
def model(x):
  return input@w.t()+b

In [53]:
pred=model(input)
pred

tensor([[  49.5510, -110.3161],
        [  62.9503, -126.1685],
        [  59.5713, -157.1709],
        [  66.2090, -153.8414],
        [  50.5477,  -84.5570]], grad_fn=<AddBackward0>)

In [54]:
print(output)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [55]:
#In the above we can see that there is a huge difference between the actual and the predicted values
#we need to evaluate our model using a loss function
#for calculating the loss we need to first calculate the difference between actual and the predicted values
#square the loss in order to remove the negative values
#THen calculate the sum of the matrix
#then calculate the average of the resultant matrix by divding with numel()
#this process is know as Mean Square Error(MSE)

def error(pred,output):
  loss=pred-output
  return torch.sum(loss*loss)/loss.numel()




In [56]:
loss=error(pred,output)  
print(loss)

tensor(25477.9277, grad_fn=<DivBackward0>)


As you can see loss is very high for our model the higher the loss the more bad is our model.now we need to improve our model,
for that we have a technique called Gradient Descent.
In pytorch we can calculate the loss automatically using gradient or derivates of the loss w.r.to the weights and biases because they have requires_grad=True.
loss.backward() computes dloss/dx for every parameter x which has requires_grad=True. These are accumulated into x.grad for every parameter x.everytime you call .backward() it keeps adding grad values to existing grad.
- Example:x.grad += dloss/dx

optimizer.step updates the value of x using the gradient x.grad. 


For example, the SGD optimizer performs:
- Example:x += -lr * x.grad
optimizer.zero_grad() clears x.grad for every parameter x in the optimizer. It’s important to call this before loss.backward(), otherwise you’ll accumulate the gradients from multiple passes.
we need to use zer_grad() otherwise the new grad values will get added to the existing grad values and this function helps grad values zero
If you have multiple losses (loss1, loss2) you can sum them and then call backwards once

In [57]:


loss.backward()

In [58]:
#Here w is the weight matrix which we initialised earlier
#here w.grad=dloss/dw
print(w)
print(w.grad)

tensor([[ 0.5977, -0.0045,  0.1303],
        [-1.7474, -0.6449,  1.3878]], requires_grad=True)
tensor([[ -1278.6971,  -2623.6665,  -1383.0555],
        [-18518.3086, -19740.5137, -12086.4834]])


In [59]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [61]:
w,b

(tensor([[ 0.5977, -0.0045,  0.1303],
         [-1.7474, -0.6449,  1.3878]], requires_grad=True),
 tensor([0.6211, 0.7784], requires_grad=True))

# For performing the Gradient descent we have a 5 step process
1-Generate predictions


2-Calculate the Loss


3-compute gradient w.r.to weights and biases


4-Adjust the weights by subracting the small quantity proportional to the gradients(we subtract the grad from weights by multiplying the grad with some value in order to make the grad value very small)


5-Reset the gradients to zero

In [62]:
#Generate Predictions
pred=model(input)
pred


tensor([[  49.5510, -110.3161],
        [  62.9503, -126.1685],
        [  59.5713, -157.1709],
        [  66.2090, -153.8414],
        [  50.5477,  -84.5570]], grad_fn=<AddBackward0>)

In [63]:
#2-Calculate the Loss
loss=error(pred,output)
loss

tensor(25477.9277, grad_fn=<DivBackward0>)

In [64]:
#3-compute gradient w.r.to weights and biases
loss.backward()
print(w.grad)
print(b.grad)

tensor([[ -1278.6971,  -2623.6665,  -1383.0555],
        [-18518.3086, -19740.5137, -12086.4834]])
tensor([ -18.4341, -218.4108])


In [65]:
#4-Adjust the weights
with torch.no_grad():
  w-=w.grad*1e-5
  b-=b.grad*1e-5
  w.grad.zero_()
  b.grad.zero_()



In [66]:
print(w)
print(b)

tensor([[ 0.6104,  0.0217,  0.1441],
        [-1.5623, -0.4475,  1.5087]], requires_grad=True)
tensor([0.6213, 0.7806], requires_grad=True)


In [68]:
pred=model(input)
loss=error(pred,output)
print(loss)

tensor(17381.7227, grad_fn=<DivBackward0>)


As you can see above the loss has decreased by a huge number.
we can perform the same task multiple times using for loop.
usually we will perform this in the form of epochs in the realtime.
Now lets traing the model using 100 epochs.

In [69]:

for i in range(100):
  pred=model(input)
  loss=error(pred,output)
  loss.backward()
  with torch.no_grad():
      w-=w.grad*1e-5
      b-=b.grad*1e-5
      w.grad.zero_()
      b.grad.zero_()
  

  



In [70]:
pred=model(input)
loss=error(pred,output)
print(loss)

tensor(233.0965, grad_fn=<DivBackward0>)


In [71]:
pred

tensor([[ 63.1935,  68.7568],
        [ 83.9066, 107.8742],
        [105.1380, 119.0721],
        [ 55.2783,  28.0567],
        [ 85.0433, 137.0543]], grad_fn=<AddBackward0>)

In [72]:
#As you can see the actual and the pred values are not having much difference as earlier
output

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

#Linear Regression using the pre-built functions of PYTORCH

In [73]:
#the below package consists of utility classes  for building NN 
import torch.nn as nn

In [74]:
inputs=np.array([[73,67,43],
                 [91,88,64],
                 [87,134,58],
                 [102,43,37],
                 [69,96,70],[37,67,43],[91,88,64],[41,88,64],[29,28,64],[31,88,84],[51,80,60],[77,48,74],[61,58,104],[75,88,64],[85,48,58]],dtype='float32')
outputs=np.array([[56,70],
                 [81,101],
                 [119,133],
                 [22,37],
                 [103,119],[13,19],[61,109],[58,52],[75,51],[61,68],[78,53],[65,83],[76,90],[51,85],[81,75]],dtype='float32')

In [75]:
print(inputs)
print(outputs)
print(inputs.shape)
print(outputs.shape)
print(type(inputs))
print(type(outputs))
print(inputs.dtype)

[[ 73.  67.  43.]
 [ 91.  88.  64.]
 [ 87. 134.  58.]
 [102.  43.  37.]
 [ 69.  96.  70.]
 [ 37.  67.  43.]
 [ 91.  88.  64.]
 [ 41.  88.  64.]
 [ 29.  28.  64.]
 [ 31.  88.  84.]
 [ 51.  80.  60.]
 [ 77.  48.  74.]
 [ 61.  58. 104.]
 [ 75.  88.  64.]
 [ 85.  48.  58.]]
[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 13.  19.]
 [ 61. 109.]
 [ 58.  52.]
 [ 75.  51.]
 [ 61.  68.]
 [ 78.  53.]
 [ 65.  83.]
 [ 76.  90.]
 [ 51.  85.]
 [ 81.  75.]]
(15, 3)
(15, 2)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
float32


In [76]:
input=torch.from_numpy(inputs)
output=torch.from_numpy(outputs)

In [77]:
print(input)
print(output)
print(input.shape)
print(output.shape)
print(type(input))
print(type(output))
print(input.dtype)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 37.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 41.,  88.,  64.],
        [ 29.,  28.,  64.],
        [ 31.,  88.,  84.],
        [ 51.,  80.,  60.],
        [ 77.,  48.,  74.],
        [ 61.,  58., 104.],
        [ 75.,  88.,  64.],
        [ 85.,  48.,  58.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 13.,  19.],
        [ 61., 109.],
        [ 58.,  52.],
        [ 75.,  51.],
        [ 61.,  68.],
        [ 78.,  53.],
        [ 65.,  83.],
        [ 76.,  90.],
        [ 51.,  85.],
        [ 81.,  75.]])
torch.Size([15, 3])
torch.Size([15, 2])
<class 'torch.Tensor'>
<class 'torch.Tensor'>
torch.float32


In [78]:
#creating a tensordataset which allows us to access rows from input and targets as tuples
#This allows us to access small set of data using array indexing
#It returns a tuple where the first element contains the inputs for the selected rows and the second element contains the target elements
#WE will also create a dataloader which will divide the data into batches of predefined size while training
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

In [79]:
#define dataset
train=TensorDataset(input,output)
train[0:4]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.]]))

In [80]:
#define dataloader
batch_size=5
data=DataLoader(train,batch_size,shuffle=True)

In [81]:
for i,j in data:
  print(i)
  print(j)
 

tensor([[ 37.,  67.,  43.],
        [ 31.,  88.,  84.],
        [102.,  43.,  37.],
        [ 51.,  80.,  60.],
        [ 87., 134.,  58.]])
tensor([[ 13.,  19.],
        [ 61.,  68.],
        [ 22.,  37.],
        [ 78.,  53.],
        [119., 133.]])
tensor([[ 29.,  28.,  64.],
        [ 73.,  67.,  43.],
        [ 61.,  58., 104.],
        [ 85.,  48.,  58.],
        [ 91.,  88.,  64.]])
tensor([[ 75.,  51.],
        [ 56.,  70.],
        [ 76.,  90.],
        [ 81.,  75.],
        [ 61., 109.]])
tensor([[77., 48., 74.],
        [41., 88., 64.],
        [69., 96., 70.],
        [91., 88., 64.],
        [75., 88., 64.]])
tensor([[ 65.,  83.],
        [ 58.,  52.],
        [103., 119.],
        [ 81., 101.],
        [ 51.,  85.]])


In [82]:
#Defining a model
#instead of assigning weights manually we will now use the inbuilt functions 
#we can define the model using nn.linear which does automatically
model=nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.0023,  0.5424,  0.0374],
        [ 0.1825, -0.2625, -0.2034]], requires_grad=True)
Parameter containing:
tensor([0.2045, 0.4457], requires_grad=True)


In [91]:
list(model.parameters())

[Parameter containing:
 tensor([[0.1228, 0.5191, 1.0057],
         [0.2066, 0.2735, 0.6698]], requires_grad=True), Parameter containing:
 tensor([-0.1258, -0.1090], requires_grad=True)]

In [92]:
#we can use the above created model to predict the outputs
pred=model(input)
pred

tensor([[ 86.8611,  62.1061],
        [121.0921,  85.6366],
        [138.4447,  93.3738],
        [ 71.9285,  57.5149],
        [128.5786,  87.2978],
        [ 82.4419,  54.6669],
        [121.0921,  85.6366],
        [114.9543,  75.3044],
        [ 82.3360,  56.4124],
        [133.8416,  86.6347],
        [108.0062,  72.5032],
        [108.6674,  78.5005],
        [142.0664,  98.0247],
        [119.1280,  82.3303],
        [ 93.5576,  69.4362]], grad_fn=<AddmmBackward>)

In [93]:
#From the above code we can see that once again the predicted outputs are quiet different from actual outputs
#now we will define the inbuilt loss function to evaluate the model
import torch.nn.functional as F

In [94]:
loss_fn=F.mse_loss
loss=loss_fn(pred,output)
loss

tensor(1387.6022, grad_fn=<MseLossBackward>)

In [95]:
#As we can see the loss is very high in order to reduce the loss we need to optimise using stocastic gradient descent(SGD)
#It is called stochastic because samples are taken as batches instead of a single group
#defining the optimizer
optim=torch.optim.SGD(model.parameters(),lr=1e-4)

In [96]:
#After creating the optimizer we need to train the model 
#For training the model we need to follow the exact same steps which we have followed earlier
def fit(epoch,model,loss,opt,train):
  for ep in range(epoch):
    for x,y in train:
      #model prediction
      pred=model(x)
      #calculate loss
      loss=loss_fn(pred,y)
      #calculate gradients
      loss.backward()
      #update the parameters using gradients
      opt.step()
      #reset the gradients to zero
      opt.zero_grad()
    if (ep+1)%10==0:
      print(ep+1,loss)  
      

In [97]:
fit(100,model,loss_fn,optim,train)

10 tensor(1126.3486, grad_fn=<MseLossBackward>)
20 tensor(1126.4591, grad_fn=<MseLossBackward>)
30 tensor(1126.5710, grad_fn=<MseLossBackward>)
40 tensor(1126.6827, grad_fn=<MseLossBackward>)
50 tensor(1126.7933, grad_fn=<MseLossBackward>)
60 tensor(1126.9058, grad_fn=<MseLossBackward>)
70 tensor(1127.0181, grad_fn=<MseLossBackward>)
80 tensor(1127.1300, grad_fn=<MseLossBackward>)
90 tensor(1127.2433, grad_fn=<MseLossBackward>)
100 tensor(1127.3564, grad_fn=<MseLossBackward>)


In [98]:
pred

tensor([[ 86.8611,  62.1061],
        [121.0921,  85.6366],
        [138.4447,  93.3738],
        [ 71.9285,  57.5149],
        [128.5786,  87.2978],
        [ 82.4419,  54.6669],
        [121.0921,  85.6366],
        [114.9543,  75.3044],
        [ 82.3360,  56.4124],
        [133.8416,  86.6347],
        [108.0062,  72.5032],
        [108.6674,  78.5005],
        [142.0664,  98.0247],
        [119.1280,  82.3303],
        [ 93.5576,  69.4362]], grad_fn=<AddmmBackward>)

In [99]:
output

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 13.,  19.],
        [ 61., 109.],
        [ 58.,  52.],
        [ 75.,  51.],
        [ 61.,  68.],
        [ 78.,  53.],
        [ 65.,  83.],
        [ 76.,  90.],
        [ 51.,  85.],
        [ 81.,  75.]])